### ISSUE TITLE
Create a way to expose the OpenAPI 3.0 spec

### ISSUE THREAD

**Issue by benjaminkostiuk** [QueueTime/qtime-backend#7]
Write an endpoint or something so that the front-end can consume the updated version of the open-api specification from the backend.
* May have to write some combining code to combine the specs for each of the endpoints into one giant spec.
* Should be a simple get endpoint. Endpoint can have no security.

## Definition of done
* Backend service exposes an endpoint where the json OpenAPI 3.0 specification can be downloaded.

**Comment by ruler225** [comment]
Accessible at /api/openapi.json
